name: CI

on: [push]

jobs:

  mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dotfiles
        run: bash install.sh

  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo curl
      - name: Install dotfiles
        run: bash install.sh


  # centos:
  #   runs-on: ubuntu-latest
  #   container: centos:latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install required packages
  #       run: yum install -y git sudo
  #     - name: Install dotfiles
  #       run: sh install.sh

  # alpine:
  #   runs-on: ubuntu-latest
  #   container: alpine:latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install required packages
  #       run: apk add git sudo bash
  #     - name: Install dotfiles
  #       run: sh install.sh

  # arch:
  #   runs-on: ubuntu-latest
  #   container: archlinux/base:latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Update packages
  #       run: pacman -Syu --noconfirm
  #     - name: Install required packages
  #       run: pacman -S --noconfirm git sudo
  #     - name: Install dotfiles
  #       run: sh install.sh
